#!/bin/zsh#!/bin/zsh
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt HIST_IGNORE_ALL_DUPS SHARE_HISTORY APPEND_HISTORY
setopt PROMPT_SUBST

autoload -Uz vcs_info
precmd_functions+=(vcs_info)
zstyle ':vcs_info:git:*' formats '%F{2}(%b)%f '
zstyle ':vcs_info:*' enable git

function zle-line-init zle-keymap-select {
  if [[ $KEYMAP == vicmd ]]; then
    VI_MODE='%F{1}[N]%f'
  else
    VI_MODE='%F{2}[I]%f'
  fi
  zle reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select

PROMPT='%F{2}%n@%m%f:%F{245}%~%f ${vcs_info_msg_0_}${VI_MODE} %# '
bindkey -v

autoload -U compinit && compinit
export TERM=foot EDITOR=nvim VISUAL=nvim
[ -n "$NVIM" ] && export GIT_EDITOR="nvr -cc split --remote-wait +'set bufhidden=wipe'" || export GIT_EDITOR="nvim"

# Editor
alias vi='nvim'
alias vim='nvim'
alias nano='nvim'

# Git
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gl='git log --oneline --graph --decorate'
alias gp='git push'
alias gpl='git pull'
alias gb='git branch'
alias gco='git checkout'
alias lg='lazygit'

# Tmux
alias tm='tmux new -As main'
alias tma='tmux attach -t'
alias tmls='tmux ls'
alias tmk='tmux kill-session -t'

# Navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# Listing
alias ls='ls --color=auto'
alias ll='ls -lah'
alias la='ls -A'
alias l='ls -CF'

# Safety
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# System
alias df='df -h'
alias du='du -h'
alias free='free -h'
alias psg='ps aux | grep -v grep | grep -i -e VSZ -e'
alias mkdir='mkdir -pv'

# Network
alias ports='netstat -tulanp'
alias ping='ping -c 5'

