set $text #ffffff
set $bg #111111ee
set $highlight #26fa84
set $error #fa2c36
set $warning #f6e162

client.focused          $highlight $bg $text $highlight $highlight
client.unfocused        $bg $bg $text $bg $bg
client.urgent           $error $bg $error $warning $error

